config/routes.rb
Rails.application.routes.draw do

  resources :permitted_users
  get 'proxy_html' => 'proxies#html'
  get 'proxy_ajax' => 'proxies#ajax'
  resources :variates

  resources :experiments, only: [:show, :new, :edit, :create, :update]

  resources :properties, only: [:index, :show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "properties#index"

end

app/models/property_user.rb
class PropertyUser < ActiveRecord::Base
  belongs_to :property
  belongs_to :user
  validates :property_id, uniqueness: {scope: :user}
end

app/controllers/property_users_controller.rb
class PropertyUsersController < ApplicationController
  before_action :set_property_user, only: [:show, :edit, :update, :destroy]

  def index
    @property_users = PropertyUser.all
    respond_with(@property_users)
  end

  def show
    respond_with(@property_user)
  end

  def new
    @property_user = PropertyUser.new
    respond_with(@property_user)
  end

  def edit
  end

  def create
    @property_user = PropertyUser.new(property_user_params)
    @property_user.save
    respond_with(@property_user)
  end

  def update
    @property_user.update(property_user_params)
    respond_with(@property_user)
  end

  def destroy
    @property_user.destroy
    respond_with(@property_user)
  end

  private
    def set_property_user
      @property_user = PropertyUser.find(params[:id])
    end

    def property_user_params
      params.require(:property_user).permit(:property_id, :user_id)
    end
end

app/helpers/property_users_helper.rb
module PropertyUsersHelper
end

app/views/property_users/_form.html.erb
<%= form_for(@property_user) do |f| %>
  <% if @property_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@property_user.errors.count, "error") %> prohibited this property_user from being saved:</h2>

      <ul>
      <% @property_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :property_id %><br>
    <%= f.number_field :property_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/property_users/edit.html.erb
<h1>Editing Property User</h1>

<%= render 'form' %>

<%= link_to 'Show', @property_user %> |
<%= link_to 'Back', property_users_path %>

app/views/property_users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Property Users</h1>

<table>
  <thead>
    <tr>
      <th>Property</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @property_users.each do |property_user| %>
      <tr>
        <td><%= property_user.property_id %></td>
        <td><%= property_user.user_id %></td>
        <td><%= link_to 'Show', property_user %></td>
        <td><%= link_to 'Edit', edit_property_user_path(property_user) %></td>
        <td><%= link_to 'Destroy', property_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Property user', new_property_user_path %>

app/views/property_users/new.html.erb
<h1>New Property User</h1>

<%= render 'form' %>

<%= link_to 'Back', property_users_path %>

app/views/property_users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Property:</strong>
  <%= @property_user.property_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @property_user.user_id %>
</p>

<%= link_to 'Edit', edit_property_user_path(@property_user) %> |
<%= link_to 'Back', property_users_path %>