config/routes.rb
Rails.application.routes.draw do

  resources :permitted_users
  get 'proxy_html' => 'proxies#html'
  get 'proxy_ajax' => 'proxies#ajax'
  resources :variates

  resources :experiments, only: [:show, :new, :edit, :create, :update]

  resources :properties, only: [:index, :show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "properties#index"

end

app/models/variate.rb
class Variate < ActiveRecord::Base
  belongs_to :experiment
end

app/controllers/variates_controller.rb
class VariatesController < ApplicationController
  before_action :set_variate, only: [:show, :edit, :update, :destroy]
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]
  respond_to :html, :xml, :json
  respond_to :js, only: [:show, :edit, :update, :create, :destroy]

  def index
    @variates = Variate.all
    respond_with(@variates)
  end

  def show
    cookies[:variate_no] = @variate.variate_no
    respond_to do |format|
      format.js
      format.html { redirect_to @variate.experiment }
    end
  end

  def new
    @variate = Variate.new(variate_params)
    respond_with(@variate)
  end

  def edit
  end

  def create
    @variate = Variate.new(variate_params)
    @variate.save
    redirect_to :controller => 'experiments', :action => 'show', :id => variate_params[:experiment_id]
  end

  def update
    @variate.update(variate_params)
    respond_to do |format|
      format.js { render :nothing => true }
      format.html { respond_with @variate }
    end
  end

  def destroy
    @variate.destroy
    respond_to do |format|
      format.js { redirect_to :controller => 'experiments', :action => 'show', :id => @experiment.id, :status => 303}
      format.html { respond_with @variate }
    end

  end

  private
    def set_variate
      @variate = Variate.find(params[:id])
    end

    def variate_params
      params.require(:variate).permit(:experiment_id, :variate_no, :js_code)
    end

    def set_experiment
      @experiment = @variate.experiment
    end
end

app/helpers/variates_helper.rb
module VariatesHelper
end

app/views/variates/_form.html.erb
<%= form_for @variate, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :experiment_id, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :experiment_id, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :variate_no, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.number_field :variate_no, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :js_code, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :js_code, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  variates_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/variates/_index.html.erb
<%- model_class = Variate -%>
<div class="variate_list" >
<div class="page-header">
  <h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
</div>
<div data-variate="js-code"></div>
  <%= link_to variate_path(0), :class => 'btn btn-primary control', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
      0
  <%- end -%>
  <% @variates.each do |variate| %>
      <div class="variate_button">

        <%= link_to variate_path(variate), :class => "btn btn-primary variate_no current_variate_#{variate.variate_no == cookies[:variate_no].to_i}", :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= variate.variate_no %>
        <%- end -%>
        <%= form_for(variate, html: {method: :patch, class: 'variate'}, remote: true, data: { :confirm => t('.confirm', :default => t("helpers.forms.confirm", :default => 'Save changes to Variate?')) })  do |f| %>
          <%= f.hidden_field :js_code %>
          <%= f.button nil, :class => 'btn btn-primary' do %>
              <%= glyph 'floppy-disk' %>
          <%- end -%>
        <% end %>
        <%= form_for(variate, html: {method: :patch, class: 'variate', id: 'variate_delete_js'}, remote: true, data: { :confirm => t('.confirm', :default => t("helpers.forms.confirm", :default => 'Delete all current Variate code?')) })  do |f| %>
          <%= f.hidden_field :js_code, :value => '' %>
          <%= f.button nil, :class => 'btn btn-primary' do %>
            <%= glyph 'trash' %>
          <%- end -%>
        <% end %>
        <%= link_to variate_path(variate), :method => :delete, remote: true, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Delete this Variate?')) }, :class => 'btn btn-primary delete', :title => "#{ t('.destroy', :default => t('helpers.links.destroy', :default => 'Delete this Variate?')) }" do %>
          <%= glyph 'remove' %>
        <%- end -%>
      </div>
      <% end %>

  <%= form_for @variate, remote: true, :html => { :class => 'form-horizontal variate add' } do |f| %>
      <%= f.hidden_field :experiment_id, :class => 'text_field form-control' %>
      <%= f.hidden_field :variate_no, :class => 'text_field form-control' %>
      <%= f.hidden_field :js_code, :class => 'text_field form-control' %>
      <%= f.button nil, :class => 'btn btn-primary' do %>
          <%= glyph 'plus' %>
      <%- end -%>
  <% end %>

</div>

app/views/variates/edit.html.erb
<%- model_class = Variate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/variates/index.html.erb
<%- model_class = Variate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:experiment_id) %></th>
      <th><%= model_class.human_attribute_name(:variate_no) %></th>
      <th><%= model_class.human_attribute_name(:js_code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @variates.each do |variate| %>
      <tr>
        <td><%= variate.id %></td>
          <td><%= variate.experiment_id %></td>
          <td><%= variate.variate_no %></td>
          <td><%= variate.js_code %></td>
        <td><%=l variate.created_at, format: :long %></td>
        <td>
          <%= link_to variate_path(variate), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_variate_path(variate), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to variate_path(variate), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_variate_path,
            :class => 'btn btn-primary' %>

app/views/variates/new.html.erb
<%- model_class = Variate -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/variates/show.html.erb
<%- model_class = Variate -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:experiment_id) %></dt>
      <dd><pre class="prettyprint"><%= @variate.experiment_id %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:variate_no) %></dt>
      <dd><pre class="prettyprint"><%= @variate.variate_no %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:js_code) %></dt>
      <dd><pre class="prettyprint"><%= @variate.js_code %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              @experiment, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_variate_path(@variate), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              variate_path(@variate),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

<h2>Variate Page</h2>
<iframe src="<%= @experiment.page_url %>" style="width:100%; height:1000px;"></iframe>

app/views/variates/show.js.erb
//location.reload();
//var dunday = "<%= raw @variate.js_code %>";
//var dunday = dunday.replace("$", "$('#variate').contents().find");
//$('#variate').contents().on('load', function () {
//    $('#variate').contents().find('body').append("<script>" + dunday + "</script>");
//});