config/routes.rb
Rails.application.routes.draw do

  resources :permitted_users
  get 'proxy_html' => 'proxies#html'
  get 'proxy_ajax' => 'proxies#ajax'
  resources :variates

  resources :experiments, only: [:show, :new, :edit, :create, :update]

  resources :properties, only: [:index, :show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "properties#index"

end

app/models/permitted_user.rb
class PermittedUser < ActiveRecord::Base
end

app/controllers/permitted_users_controller.rb
class PermittedUsersController < ApplicationController
  before_action :set_permitted_user, only: [:show, :edit, :update, :destroy]
  before_action :is_user_admin

  respond_to :html

  def index
    @permitted_users = PermittedUser.all
    respond_with(@permitted_users)
  end

  def show
    respond_with(@permitted_user)
  end

  def new
    @permitted_user = PermittedUser.new
    respond_with(@permitted_user)
  end

  def edit
  end

  def create
    @permitted_user = PermittedUser.new(permitted_user_params)
    @permitted_user.save
    respond_with(@permitted_user)
  end

  def update
    @permitted_user.update(permitted_user_params)
    respond_with(@permitted_user)
  end

  def destroy
    @permitted_user.destroy
    respond_with(@permitted_user)
  end

  private
    def set_permitted_user
      @permitted_user = PermittedUser.find(params[:id])
    end

    def permitted_user_params
      params[:permitted_user]
    end

    def is_user_admin
      unless current_user.administrator
        redirect_to(:back)
      end
    end
end

app/helpers/permitted_users_helper.rb
module PermittedUsersHelper
end

app/views/permitted_users/_form.html.erb
<%= form_for @permitted_user, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="form-group">
    <%= f.label :email, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :email, :class => 'text_field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  permitted_users_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/permitted_users/edit.html.erb
<%- model_class = PermittedUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permitted_users/index.html.erb
<%- model_class = PermittedUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @permitted_users.each do |permitted_user| %>
      <tr>
        <td><%= permitted_user.id %></td>
          <td><%= permitted_user.email %></td>
        <td><%=l permitted_user.created_at, format: :long %></td>
        <td>
          <%= link_to permitted_user_path(permitted_user), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_permitted_user_path(permitted_user), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to permitted_user_path(permitted_user), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_permitted_user_path,
            :class => 'btn btn-primary' %>

app/views/permitted_users/new.html.erb
<%- model_class = PermittedUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/permitted_users/show.html.erb
<%- model_class = PermittedUser -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:email) %></dt>
      <dd><pre class="prettyprint"><%= @permitted_user.email %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              permitted_users_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_permitted_user_path(@permitted_user), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              permitted_user_path(@permitted_user),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>