config/routes.rb
Rails.application.routes.draw do

  resources :permitted_users
  get 'proxy_html' => 'proxies#html'
  get 'proxy_ajax' => 'proxies#ajax'
  resources :variates

  resources :experiments, only: [:show, :new, :edit, :create, :update]

  resources :properties, only: [:index, :show]

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  root :to => "properties#index"

end

app/models/experiment.rb
class Experiment < ActiveRecord::Base
  belongs_to :property
  has_many :variates
end

app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update]
  before_action :set_property, only: [:show, :edit, :update]
  before_action :set_uri_domain, only: [:show]

  respond_to :html, :xml, :json

  # TODO These are viewable even when not logged in. Fix this. Or maybe they're not. confused :-s

  def index
    @experiments = Experiment.all
    respond_with(@experiments)
  end

  def show
    @variates = @experiment.variates
    @new_variate_no = @variates.empty? ? 1 : @variates.last.variate_no + 1
    @variate = Variate.new({experiment_id: @experiment.id, variate_no: @new_variate_no})
    @variate_js = ''
    @current_variate = @variates.find_by(variate_no: cookies[:variate_no])
    begin
      @variate_js = @current_variate[:js_code].gsub!(/\$/, "$('#variate').contents().find")
    rescue NoMethodError
      @variate_js = ''
    end
    respond_to do |format|
      format.js
      format.html { respond_with(@experiment) }
    end

  end

  def new
    @experiment = Experiment.new(experiment_params)
    respond_with(@experiment)
  end

  def edit
  end

  def create
    @experiment = Experiment.new(experiment_params)
    @experiment.save
    respond_with(@experiment)
  end

  def update
    @experiment.update(experiment_params)
    respond_with(@experiment)
  end

  def destroy
    @experiment.destroy
    respond_with(@experiment)
  end

  private
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    def experiment_params
      params.require(:experiment).permit(:property_id, :name, :date_from, :date_to, :live, :page_url, :unique_identifier, :js_code)
    end

    def set_property
      @property = @experiment.property
    end

    def set_uri_domain
      @uri_domain = URI.parse(@experiment.page_url).host
    end
end

app/helpers/experiments_helper.rb
module ExperimentsHelper
end

app/views/experiments/_form.html.erb
<%= form_for @experiment, :html => { :class => 'form-horizontal' } do |f| %>
  <!--<div class="form-group">-->
    <!--<%= f.label :property_id, :class => 'control-label col-md-2' %>-->
    <!--<div class="col-md-10">-->
      <!--<%= f.text_field :property_id, :class => 'text_field form-control' %>-->
    <!--</div>-->
  <!--</div>-->
  <div class="form-group">
    <%= f.label :name, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :name, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_from, :class => 'control-label col-md-2' %>
    <div class="col-md-10 form-inline">
      <%= f.datetime_select :date_from, {}, :class => 'form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_to, :class => 'control-label col-md-2' %>
    <div class="col-md-10 form-inline">
      <%= f.datetime_select :date_to, {}, :class => 'form-control' %>
    </div>
  </div>
  <!--<div class="form-group">-->
    <!--<%= f.label :live, :class => 'control-label col-md-2' %>-->
    <!--<div class="col-md-1">-->
      <!--<%= f.check_box :live, :class => 'form-control' %>-->
    <!--</div>-->
  <!--</div>-->
  <div class="form-group">
    <%= f.label :page_url, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :page_url, :class => 'text_field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :unique_identifier, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :unique_identifier, :class => 'text_field form-control' %>
    </div>
  </div>
  <!--<div class="form-group">-->
    <!--<%= f.label :js_code, :class => 'control-label col-md-2' %>-->
    <!--<div class="col-md-10">-->
      <!--<%= f.text_area :js_code, rows: 5, :class => 'text_field form-control' %>-->
    <!--</div>-->
  <!--</div>-->

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <!-- TODO: Is request.referrer the correct choice here? -->
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  @property, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/experiments/_index.html.erb
<%- model_class = Experiment -%>
<h2><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h2>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:date_from) %></th>
    <th><%= model_class.human_attribute_name(:date_to) %></th>
    <th><%= model_class.human_attribute_name(:live) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.name %></td>
        <td><%= experiment.date_from %></td>
        <td><%= experiment.date_to %></td>
        <td><%= experiment.live %></td>
        <td>
          <%= link_to experiment_path(experiment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
              <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_experiment_path(experiment), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
              <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to experiment_path(experiment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
              <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_experiment_path(experiment: {property_id: params[:id]}),
            :class => 'btn btn-primary' %>

app/views/experiments/edit.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiments/index.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:property_id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:date_from) %></th>
      <th><%= model_class.human_attribute_name(:date_to) %></th>
      <th><%= model_class.human_attribute_name(:live) %></th>
      <th><%= model_class.human_attribute_name(:page_url) %></th>
      <th><%= model_class.human_attribute_name(:unique_identifier) %></th>
      <th><%= model_class.human_attribute_name(:js_code) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.id %></td>
          <td><%= experiment.property_id %></td>
          <td><%= experiment.name %></td>
          <td><%= experiment.date_from %></td>
          <td><%= experiment.date_to %></td>
          <td><%= experiment.live %></td>
          <td><%= experiment.page_url %></td>
          <td><%= experiment.unique_identifier %></td>
          <td><%= experiment.js_code %></td>
        <td><%=l experiment.created_at, format: :long %></td>
        <td>
          <%= link_to experiment_path(experiment), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
          <%- end -%>
          <%= link_to edit_experiment_path(experiment), :class => 'btn btn-xs', :title => "#{ t('.edit', :default => t('helpers.links.edit')) }" do %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to experiment_path(experiment), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_experiment_path,
            :class => 'btn btn-primary' %>

app/views/experiments/new.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiments/show.html.erb
<%- model_class = Experiment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              @property, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_experiment_path(@experiment), :class => 'btn btn-default' %>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:name) %></dt>
      <dd><pre class="prettyprint"><%= @experiment.name %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date_from) %></dt>
      <dd><pre class="prettyprint"><%= @experiment.date_from %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date_to) %></dt>
      <dd><pre class="prettyprint"><%= @experiment.date_to %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:page_url) %></dt>
      <dd><pre class="prettyprint"><%= @experiment.page_url %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:unique_identifier) %></dt>
      <dd><pre class="prettyprint"><%= @experiment.unique_identifier %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:js_code) %></dt>
      <dd><pre class="prettyprint"><%= @experiment.js_code %></pre></dd>
  </dl>
</div>

<%= render 'variates/index' %>

<h2>Original Page</h2>

<div class="dropdown">
  <iframe src="<%= raw proxy_html_path(proxy: {uri: @experiment.page_url}) %>" id="variate" style="width:100%; height:1000px;">

  </iframe>
</div>

<script>
  var emvt = emvt || {};
  emvt.pageDomain = '<%= @uri_domain %>';
        clonedDom = $('#variate').clone(true, true);
</script>

<!-- TODO Aria classes? -->
<ul class="dropdown-menu variate-menu" draggable="true">
  <li class="dropdown-header" ><span>Current Element</span></li> <!-- Header -->
  <li data-emvt-element="current"><span class="glyphicon glyphicon-stop"></span> <span class="text">Current</span></li>
  <li class="divider"></li>
  <!--<li class="dropdown-header" >Select Relative</li> &lt;!&ndash; Header &ndash;&gt;-->

  <li class="dropdown-header"><span data-toggle="collapse" data-target="#selectToggle">Select Relative</span> <!-- Header -->
    <ul id="selectToggle" class="collapse in">
      <li data-emvt-relative="selectParent"><span class="glyphicon glyphicon-triangle-top"></span> <span class="text">Parent</span></li>
      <li data-emvt-relative="selectFirstChild"><span class="glyphicon glyphicon-triangle-bottom"></span> <span class="text">FirstChild</span></li>
      <li data-emvt-relative="selectNextSibling"><span class="glyphicon glyphicon-triangle-right"></span> <span class="text">Next Sibling</span></li>
      <li data-emvt-relative="selectPreviousSibling"><span class="glyphicon glyphicon-triangle-left"></span> <span class="text">Previous Sibling</span></li>
    </ul>
  </li>
  <li class="divider"></li>
  <li class="dropdown-header"><span data-toggle="collapse" data-target="#moveToggle">Move Element</span> <!-- Header -->
    <ul id="moveToggle" class="collapse in">
      <li data-emvt-element="moveUp"><span class="glyphicon glyphicon-arrow-up"></span> <span class="text">Into Grandparent</span></li>
      <li data-emvt-element="moveDown"><span class="glyphicon glyphicon-share-alt"></span> <span class="text">Into Next Sibling</span></li>
      <li data-emvt-element="moveRight"><span class="glyphicon glyphicon-arrow-right"></span> <span class="text">After Next Sibling </span></li>
      <li data-emvt-element="moveLeft"><span class="glyphicon glyphicon-arrow-left"></span> <span class="text">Before Previous Sibling</span></li>
    </ul>
  </li>
  <li class="divider"></li>
</ul>
<!--
<li><a tabindex="-1" href="#">text</a></li> &lt;!&ndash; Normal menu item &ndash;&gt;
<li data-emvt="menu-parent"><span class="glyphicon glyphicon-menu-up"></span> <span class="text"></span></li>
<li data-emvt="menu-firstchild"><span class="glyphicon glyphicon-menu-down"></span> <span class="text"></span></li>
<li data-emvt="menu-tagname">tagname: <span class="text"></span></li>
<li data-emvt="menu-id">id: <span class="text"></span></li>
<li data-emvt="menu-classes">classes: <span class="text"></span></li>
<li data-emvt="menu-text">text: <span class="text"></span></li>
<li class="divider"></li> &lt;!&ndash; Header &ndash;&gt;
<li class="disabled"><a tabindex="-1" href="#">text</a></li> &lt;!&ndash; Disabled menu item &ndash;&gt;
-->
<script>
    $(window).on('load', function () {
        <%= raw @variate_js %>
    });
</script>

app/views/experiments/show.js.erb
$('.variate_list').html("<%= escape_javascript(render 'variates/index') %>");